version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-crudapi
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crudapi
    ports:
      - "5432:5432"