spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crudapi
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
jwt:
  secret:
  expiration: 360000